# Generated by Django 4.2.6 on 2023-10-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellidos", models.CharField(max_length=255)),
                ("nombres", models.CharField(max_length=255)),
                ("fecha_inscripcion", models.DateField(null=True)),
            ],
        ),
    ]
