# Generated by Django 4.2.6 on 2023-10-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("estudiantes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("creditos", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudiantes.curso",
                    ),
                ),
                (
                    "id_estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estudiantes.estudiante",
                    ),
                ),
            ],
        ),
    ]
