# Generated by Django 4.2.6 on 2023-10-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudiantes", "0002_curso_inscripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="id_estudiante",
            field=models.IntegerField(null=True),
        ),
    ]
