# Generated by Django 4.2.6 on 2023-10-09 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("estudiantes", "0003_estudiante_id_estudiante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscripcion",
            name="id_curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="estudiantes.curso",
            ),
        ),
    ]
