# Generated by Django 4.2.6 on 2023-10-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estudiantes", "0006_remove_estudiante_id_estudiante"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="id_curso",
            field=models.IntegerField(null=True),
        ),
    ]
