# Generated by Django 4.2.6 on 2023-10-09 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estudiantes", "0008_remove_curso_id_curso_estudiante_id_estudiante"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estudiante",
            name="id_estudiante",
        ),
    ]
