# Generated by Django 4.2.6 on 2023-10-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_curso", models.IntegerField(null=True)),
                ("id_estudiante", models.IntegerField(null=True)),
            ],
        ),
    ]
